services:
  tedge:
    build:
      dockerfile: images/main.dockerfile
      context: .
    privileged: true

  child01:
    build:
      dockerfile: images/child.dockerfile
      context: .
    privileged: true
