name: test
permissions:
  contents: write
on:
  pull_request:
  workflow_dispatch:
jobs:
  release:
    name: Package and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: extractions/setup-just@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.20.0'
          cache: false
      - run: go install github.com/goreleaser/nfpm/v2/cmd/nfpm@latest
        name: Install dependencies

      - name: Package
        run: just build
